## Numpy 설치하기

In [1]:
# Numpy 설치하기
# !uv add numpy

import numpy as np
print(np.__version__)



2.5.1


In [4]:
#!pip list | grep numpy
# windows에는 기본적으로 grep대시 findstr이 탑재되어 있음
!uv pip list| findstr numpy


numpy                   2.5.1


In [5]:
import time

# 1,000만 개의 원소를 가진 파이썬 리스트 생성
py_list = list(range(10000000))

# 연산 시간 측정시작
start_time = time.time()

# for 루프 또는 컴프리헨션을 이용한 각 원소 2배 연산
result_list = [x * 2 for x in py_list]

print(f"파이썬 리스트 소요 시간: {time.time() - start_time:.4f} 초")

파이썬 리스트 소요 시간: 0.7094 초


In [7]:
np.arange(10)  # ([start,] stop [,step])

	# python을 이용한 계산
	%time sum(range(1000000))

IndentationError: unexpected indent (2179137124.py, line 4)

In [6]:
import numpy as np

# 1,000만 개의 원소를 가진 NumPy 배열 생성
np_array = np.arange(10000000)

# 연산 시간 측정시작
start_time = time.time()

# 반복문 없이 배열 전체에 바로 2를 곱하는 벡터화 연산
result_array = np_array * 2

print(f"NumPy 배열 소요 시간: {time.time() - start_time:.4f} 초")

NumPy 배열 소요 시간: 0.0223 초


In [8]:
np.arange(10)  # ([start,] stop [,step])
# numpy을 이용한 계산
%time np.sum(np.arange(1000000))

CPU times: total: 0 ns
Wall time: 6.26 ms


np.int64(499999500000)

In [9]:
import numpy as np

# 2행 3열의 수치형 2차원 배열 정의
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

print("배열의 차원:", arr.ndim, np.ndim(arr))   # 출력: 2
print("배열의 형태:", arr.shape, np.shape(arr))  # 출력: (2, 3)
print("원소 총 개수:", arr.size, np.size(arr))  # 출력: 6
print("데이터 타입:", arr.dtype)  # 출력: int64 - bit  => 8 byte

# 정수형 데이터를 실수형(Float) 데이터 타입으로 강제 변환
float_arr = arr.astype(np.float64)
print("변경된 타입:", float_arr.dtype)  # 출력: float64


배열의 차원: 2 2
배열의 형태: (2, 3) (2, 3)
원소 총 개수: 6 6
데이터 타입: int64
변경된 타입: float64


In [11]:
import numpy as np

a = np.array([1, 2, 3])
print(type(a))            # <class 'numpy.ndarray'>
print(a.dtype)            # int64 : 정수 64bit => 8byte

<class 'numpy.ndarray'>
int64


In [12]:
import numpy as np

int64_a = np.array([1, 2, 3])
print(int64_a.dtype )
float32_b = int64_a.astype(np.float32)      # 'as~'가 들어가는 함수는 타입 변경의미
print(float32_b )                 # array([1., 2., 3.])
print(float32_b .dtype)           # dtype('float32')

int64
[1. 2. 3.]
float32


### 다양하고 편리한 배열 생성 함수들

array: Python 리스트나 튜플을 배열로 변환.
zeros: 모든 값이 0인 배열 생성.
ones: 모든 값이 1인 배열 생성.
eye: 단위행렬(identity matrix)로(행,열,위치)로 생성.
identity: 수학에서 단위행렬로 크기 한 개만 지정
full: 지정된 값으로 채워진 배열 생성.
empty: 초기화되지 않은 배열 생성
linspace: 시작과 끝 값 사이를 균등하게 나눈 값을 가지는 배열 생성.
logspace : linspace과 비슷하며 log scale을 사용.
arange: 일정한 간격의 값을 가지는 배열 생성.
random.rand: 균등 분포에서 난수 배열 생성.
random.randn: 정규 분포에서 난수 배열 생성.

In [13]:
# 1차원 배열 = 벡터
a = np.array([1,2,3])
print(a)           # [1 2 3]
print(dir(a))
print(type(a))     # <class 'numpy.ndarray'>
print(a.shape)     # print(a.shape)

[1 2 3]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '_

In [14]:
# 2차원 배열 = 행렬
b = np.array([[1,2],[3,4]]) # 2행 2열
print(b)                # [[1 2][3 4]]
print(dir(b))
print(type(b))           # <class 'numpy.ndarray'>
print(b.shape)           # (2, 2)

[[1 2]
 [3 4]]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd

In [15]:
# 1차원 배열 = 벡터
a = np.array([1,2,3])
print(a)           # [1 2 3]
print(dir(a))
print(type(a))     # <class 'numpy.ndarray'>
print(a.shape)     # print(a.shape)

[1 2 3]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '_

In [16]:
# 2차원 배열 = 행렬
b = np.array([[1,2],[3,4]]) # 2행 2열
print(b)                # [[1 2][3 4]]
print(dir(b))
print(type(b))           # <class 'numpy.ndarray'>
print(b.shape)           # (2, 2)

[[1 2]
 [3 4]]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd

In [18]:
# 3차원 배열 = 텐서(tensor)
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # 2층(공간, 면), 2행 , 2열
print(c)          # [[[1,2][3,4]]  
                  # [[5,6][7,8]]]
print(dir(c))
print(type(c))     # <class 'numpy.ndarray'>
print(c.shape)     # (2, 2, 2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__

In [19]:
# 문자 데이터가 하나라도 있으면 전체가 문자로 바뀐다.
# numpy는 homogeneous 즉 같은 데이터 타입만 저장 할 수 있다.
a = np.array([1, '2', 3])
print(a)             # ['1' '2' '3']

['1' '2' '3']


In [20]:
a = np.array(['a', 1, True])
print(a)              # array(['a', '1', 'True'], dtype='<U21')

['a' '1' 'True']


In [21]:
a = np.array([True, False, True])
print(a)               # array([ True, False,  True])

[ True False  True]


In [22]:
a = np.array([True, False, True, 0, 1]) # False -> 0, True -> 1
print(a)                 #  array([1, 0, 1, 0, 1])

[1 0 1 0 1]


In [23]:
a = np.zeros(3) 
print(a)        # [0. 0. 0.]


[0. 0. 0.]


In [24]:
a = np.zeros((2, 3))
print(a)        # [[0. 0. 0.]
                # [0. 0. 0.]]

[[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
a = np.ones(3)
print(a)        # [1. 1. 1.]

[1. 1. 1.]


In [26]:
a = np.ones((2, 3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [27]:
# ### np.eye(x, y, k)

# - eye는 단위행렬로 x행, x열 값 생성(대각선 값은 1로, 나머지는 0)
# - 숫자만 사용할 수 있다.
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
# 3행 2열의  단위 행렬 생성
a = np.eye(3, 2) # 3행 2열
print(a)                 # [[1. 0.][0. 1.][0. 0.]]

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [29]:
# 1를 시작되는 위치를 지정할 수 있다. (k=1)
a = np.eye(3, 4, k=1) # 3행 4열
print(a)                 # [[0. 1. 0. 0.]
                         # [0. 0. 1. 0.]
                         # [0. 0. 0. 1.]]

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
a = np.identity(3)
print(a)                  # [[1. 0. 0.][0. 1. 0.][0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
a = np.full((2,2), 1)
print(a)

[[1 1]
 [1 1]]


In [ ]:
a = np.full((2,2), [1, 2])
print(a)

In [32]:
a = np.full((2, 2), [[1], [2]])
print(a)

[[1 1]
 [2 2]]


In [34]:
a = np.full((2,2), [[1,2],[3,4]])  # np.full(shape, fill_value)
print(a)                     # [[1 2][3 4]]

[[1 2]
 [3 4]]


In [ ]:
a = np.empty(3)
print(a)    # [1. 1. 1.] : 실행할 때마다 값은 바뀔수 있다.

[1. 1. 1.]


In [ ]:
a = np.empty((2, 3))
print(a)        # [[1. 0. 0.]
                # [1. 0. 0.]]

[[1. 0. 0.]
 [1. 0. 0.]]


### linspace

- 동등한 간격으로 값을 생성한다.
- 0부터 49까지 50개가 생성된다면 세 번째 num인자 값이 생략되여 있으므로 start와 end 계산해서 default 50이 생성된다.
- linspace(start, end, num)
- linspace (0, 49) #num의 default value 50

In [41]:
a = np.linspace(0, 49)
print(a)             # [0.  1.  2. 3. ... 49.]    

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]


In [42]:
a = np.linspace(0, 5)
print(a)

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]


In [44]:
# endpoint=False로 설정하면 5가 포함이 안된다.
a = np.linspace(0, 5, endpoint=False)
print(a)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]


**arange**

numpy.arange([**start**, ]stop, [step, ]dtype=**None**)

- start: 생성할 배열의 시작 값 (기본값은 0)
- stop: 생성할 배열의 종료 값 (이 값은 포함되지 않음)
- step: 숫자 사이의 간격 (기본값은 1)
- dtype: 생성할 배열의 데이터 타입 (옵션)

In [45]:
# 기본 사용법
# 0부터 9까지의 숫자 배열 생성
arr = np.arange(10)
print(arr)              # [0 1 2 3 4 5 6 7 8 9]

[0 1 2 3 4 5 6 7 8 9]


In [46]:
# 시작 값과 종료 값 설정
arr = np.arange(3, 10)  # 3부터 9까지
print(arr)              # [3 4 5 6 7 8 9]

[3 4 5 6 7 8 9]


In [47]:
# 간격 설정
arr = np.arange(1, 10, 2)  # 1부터 9까지 2씩 증가
print(arr)                 # [1 3 5 7 9]

[1 3 5 7 9]


In [ ]:
# 실수 간격 사용
arr = np.arange(0, 1, 0.1)  # 0부터 1까지 0.1씩 증가
print(arr)      # [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


### _like

- _like가 붙으면 shape이 같게 만들어진다.
- 연산하기 위해서 shape을 맞춰야 하는 경우가 있다.
- 기존 배열의 모양만 가져옴

In [51]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

b = np.ones_like(a)
print(b)


[[1 2 3]
 [4 5 6]]
[[1 1 1]
 [1 1 1]]


In [52]:
a = np.array([[1., 2., 3.], [4., 5., 6.]])
print(a)

b = np.empty_like(a)
print(b)
             

[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [53]:
a = np.array([[1., 2., 3.], [4., 5., 6.]])
print(a)

b = np.zeros_like(a)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [57]:
np.random.seed(42)

num = np.random.rand(2, 3)
print(num)

normal_dist_matrix = np.random.randn(3, 3)
print(normal_dist_matrix)

lotto_numbers = np.random.randint(1, 46, size=6)
print(lotto_numbers)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]
[[ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783]]
[42 28 16 15 44  3]


In [58]:
# 동일한 난수 결과 발생을 위한 난수 시드 값 고정
np.random.seed(42)

num = np.random.rand(2, 3)
print(num)

# 평균 0, 표준편차 1 구조를 만족하는 3행 3열의 정규분포 매트릭스 빌드
normal_dist_matrix = np.random.randn(3, 3)
print(normal_dist_matrix)   # [[-0.23415337 ... 0.24196227]]


# 1부터 46 미만의 범위에서 무작위 로또 번호 숫자를 닮은 6개 정수 생성
lotto_numbers = np.random.randint(1, 46, size=6)
print(lotto_numbers)     # [39 29 15 43  8 21]


[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]
[[ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783]]
[42 28 16 15 44  3]


In [61]:
np.array

<function numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, ndmax=0, like=None)>

In [62]:
help(np.array)


Help on built-in function array in module numpy:

array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, ndmax=0, like=None)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          ndmax=0, like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or i

In [ ]:
# shadow copy
a = [1, 2, 3]        # list
b = a       # shadow copy
print(b)
print(a is b )        # 메모리 주소 비교 True
b[0] = 7
print(a)               # [7, 2, 3]           
print(b)                # [7, 2, 3]




[1, 2, 3]
True
[7, 2, 3]
[7, 2, 3]


In [65]:
a = [1,2,3]
b = a.copy()        # deep copy : 주소값만 복사
id(a)                 # 133162358434304
id(b)                 # 133162358425280
print(a is b)         # 주소 비교 False
print(a == b)         # 값 비교 True

b[0] = 8
# a는 안바뀐다.
print(a)               # [1, 2, 3]
print(b)               # [8, 2, 3]
print(a is b)          # 메모리 주소 비교  False
print(a == b)          # 값 비교           False

False
True
[1, 2, 3]
[8, 2, 3]
False
False


In [66]:
a = [[1,2,3]]
print(type(a))           # list

b = a.copy()
print(id(a))              # 133162358428608
print(id(b))              # 133162358989568

print(a is b)             # False
print(a == b)             # True 

b[0][0] = 10
print(a[0])               # [10, 2, 3]
print(b[0])               # [10, 2, 3]

<class 'list'>
2603663844032
2604642238592
False
True
[10, 2, 3]
[10, 2, 3]


In [ ]:
import copy
a = [[1, 2, 3]]

# list가 2차원일때 deep copy을 하기 위해서 copy모듈에 있는 
# deepcopy메소드를 사용한다.
b = copy.deepcopy(a)
print(a[0] is b[0])
print(a[0] == b[0])

b[0][0] = 10

print(a[0] is b[0])
print(a[0] == b[0])

print(a)
print(b)

False
True
False
False
[[1, 2, 3]]
[[10, 2, 3]]


[:] 는 전체라는 뜻이다. ':' - 슬라이싱

슬라이싱 방식으로 1차 리스트일때는 재할당하면 deep copy가 된다.

슬라이싱 방식으로 2차 리스트 이상인 경우는 shallow copy가 발생된다.

In [68]:
a = [1,2,3]
b = a[:]
print(a)                      # [1,2,3]
print(b)                      # [1,2,3]

b[0] = 10
print(a)                      # [1, 2, 3]
print(b)                      # [10, 2, 3]

a = [[1,2,3]]
b = a[:]
print(a is b)                 # False
print(a == b)                 # True

 # 메모리 주소 비교  => 2차원일때 deepcopy 가 발생되지 않음
print(a[0][0] is b[0][0])                    #True
print(a[0][0] == b[0][0])  # 값비교           True


[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
[10, 2, 3]
False
True
True
True


In [69]:
a = b = np.array([1,2,3])
print(a is b)                         # True
print(a == b)                         # [ True  True  True]

a[0] = 100
print(a[0])                           # 100
print(b[0])                           # 100


a = np.array([1,2,3])
b = a.copy()

print(a is b)                           # 메모리 주소 False      
print(a == b)                           # 값 [ True  True  True]

True
[ True  True  True]
100
100
False
[ True  True  True]


In [70]:
import numpy as np

# create a numpy array
numbers = np.array([1, 3, 5, 7, 9])

# access the last element
print(numbers[-1])    # prints 9

# access the second-to-last element
print(numbers[-2])    # prints 7

9
7


2) 2차원 매트릭스 인덱싱 ([행, 열])

- 리스트의 중첩 구조(`arr[][]`)와 달리, 넘파이는 단일 대괄호 내부에 쉼표 하나로 행과 열을 동시에 제어 (`arr[행, 열]`).
- 0번째 축(`axis=0`, 행)과 1번째 축(`axis=1`, 열)의 인덱스가 각각 독립적이고 유기적으로 결합되어 작동

In [71]:
import numpy as np

# 3행 3열 구조의 2차원 기본 배열 정의
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 1번 행의 2번 열 데이터 단독 호출 ➔ 값: 6
target_value = arr[1, 2]
print(target_value)  # 출력 결과: 6


6


## 2.2 불리언 인덱싱 (Boolean Indexing)

- 조건 필터링 (예: 특정 값 이상인 데이터만 골라내기)
- 배열의 각 원소에 조건식(예: `arr > 5`)을 적용하여 참(`True`)과 거짓(`False`)으로 구성된 조건 배열 생성
- 생성된 불리언 배열을 기존 배열의 인덱스로 주입하여 `True`인 위치의 값만 필터링하여 반환

In [72]:

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 불리언 인덱싱: 5보다 큰 데이터만 필터링
bool_mask = arr > 5
print(arr[bool_mask])  # 출력: [6, 7, 8, 9]

[6 7 8 9]


In [74]:

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 불리언 인덱싱: 5보다 큰 데이터만 필터링
# bool_mask = arr > 5
print(arr[arr > 5])  # 출력: [6, 7, 8, 9]

[6 7 8 9]


In [76]:
arr = np.array([
    [0, 1, 2, 3],
    [4, 5, 6,7],
    [8, 9, 10, 11]
])

axis_ABC = ['A', 'A', 'B', 'C', 'C']

bool_mask = arr[axis_ABC == 'A']
print(arr[bool_mask])  # 출력: [[0,1,2,3], [4,5,6,7]]
                        

[]


## 2.3 팬시 인덱싱 (Fancy Indexing)

- 특정 인덱스 배열을 전달하여 비연속적인 데이터 추출하기
- 정수형 레이블이나 인덱스 번호가 담긴 리스트/배열을 전달하여 원하는 위치의 데이터를 한 번에 추출
- 연속적이지 않고 무작위로 떨어져 있는 특정 행이나 열을 임의로 골라낼 때 유용하게 활용

In [78]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 팬시 인덱싱: 0번 행과 2번 행만 선택하여 추출
print(arr[[0, 2]])

[[1 2 3]
 [7 8 9]]


In [ ]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [9, 10, 11],
    [12, 13, 14]
])

# print(arr[[1: 2]]) : ':' 슬라이싱인덱스를 사용할 수 없다. 
print(arr[[1, 2]])     # [[3, 4,5], [6, 7, 8]], 비연속적 데이터에는 슬라이싱을 사용할 수 없다.

print(arr[[-1, -2]])    # [[12, 13, 14], [9, 10, 11]]

[[3 4 5]
 [6 7 8]]
[[12 13 14]
 [ 9 10 11]]


## 2.4   팬시 인덱싱과 불리언 차이

- indexing은 원래 차원에서 하나 감소해서 가져오고 fancy indexing은 원래 차원 그대로 가져온다.

In [82]:
a = np.arange(24).reshape(2,3,4) # 3차원(2층(면, 공간), 3행, 4열)
print(a)                # reshape()

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [89]:
# indexing은 차원이 하나 감소해서 가져온다. (3차원을 2차원으로 가져온다.)
a[0]


# array([[ 0,  1,  2,  3],        # 데이터 값을 가져올때 원래의 값을 가져오느나 축소해서 가져오느냐?
#       [ 4,  5,  6,  7],
#      [ 8,  9, 10, 11]])


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
# indexing은 차원이 하나 감소해서 가져온다. (3차원을 2차원으로 가져온다.)
a[0]


#array([[ 0,  1,  2,  3],
#       [ 4,  5,  6,  7],
#       [ 8,  9, 10, 11]])


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
# fancy indexing은 원래 3차원 그대로 가져온다.
a[[0]]

#```
#array([[[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]]])
#```

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

ellipsis

- …(ellipsis)은 이후의 모든 것을 의미한다.

In [92]:
a[0]=a[0, :, :]=a[0,...]
print(a[0])  # indexing 기법
print(a[0, :, :]) # slicing 기법
print(a[0,...])  # ellipsis 기법(생략기법)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
type(...)       # ellipsis

ellipsis

In [94]:
a[[0], :, :]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [95]:
a[0, :, 1]

array([1, 5, 9])

In [ ]:
a[[0], :, [1]]      # 팬시 인덱싱

array([[1, 5, 9]])

In [97]:
a[[0], :, [1, 3]]

array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [98]:
a[:, 1, :]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [102]:
a = np.arange(24).reshape(2,3,4) # 3차원(2층(면, 공간), 3행, 4열)
print(a) 

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [103]:
b = a[:, [1], :]
b.shape

(2, 1, 4)

In [106]:
b = a[[1], :, :]
b.shape

(1, 3, 4)

In [107]:
a[:, :, [1]]

array([[[ 1],
        [ 5],
        [ 9]],

       [[13],
        [17],
        [21]]])

In [108]:
a[:, :, -1]

array([[ 3,  7, 11],
       [15, 19, 23]])

In [109]:
a[..., -1]

array([[ 3,  7, 11],
       [15, 19, 23]])

줄임표현(…)

출력해야할 데이터 수가 엄청 클 때 보이는 ...은 ellipsis와 다르다

In [110]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999], shape=(10000,))

In [111]:
np.set_printoptions(edgeitems=6)

np.arange(10000)

array([   0,    1,    2,    3,    4,    5, ..., 9994, 9995, 9996, 9997,
       9998, 9999], shape=(10000,))

## 2.5 배열의 형태 변형 (Reshaping)

`reshape()`, `flatten()`, `ravel()의 차이점 및 활용`

 1) reshape 함수와 -1의 의미

- 원소의 총 개수를 유지하면서 배열의 차원과 모양(`shape`)을 자유자재로 변경하는 핵심 함수
- 형태 지정 시 한 축에 `-1`을 대입하면, 전체 원소 개수를 기반으로 나머지 축의 크기를 컴퓨터가 자동으로 계산하여 배치

 2) 1차원 평탄화: flatten과 ravel의 차이점

- `flatten()`: 다차원 배열을 1차원 배열로 완전히 풀어버리며, 원본과 분리된 새로운 메모리 '복사본(Copy)'을 생성

In [ ]:
arr = np.array([[1, 2], [3, 4]])

dap = arr.flatten()
print(dap)                      # 출력 : [1 2 3 4]


# 메모리 공유 확인:: False
# shares는 객체 모양까지 비교
print(f'메모리 공유 확인:: {np.shares_memory(arr, dap)}')
print(f'{arr is dap}')      

[1 2 3 4]
메모리 공유 확인:: False
False


In [ ]:
# 1차원 12개 원소 배열을 3행 4열 2차원 배열로 변경
arr_1d = np.arange(12)
arr_2d = arr_1d.reshape(3, 4)

# 메모리 공유 확인:: True
print(f'메모리 공유 확인:: {np.shares_memory(arr_1d ,arr_2d)}') 
print(arr_1d is arr_2d)     # 벡터로 비교

메모리 공유 확인:: True
False


In [117]:
# 행의 크기는 2로 지정하고, 열의 크기는 자동 계산(-1)하여 배치
arr_auto = arr_1d.reshape(2, -1)  # 결과적으로 2행 6열로 자동 변환됨

# 메모리 공유 확인:: True
print(f'메모리 공유 확인:: {np.shares_memory(arr_1d,arr_auto)}')

메모리 공유 확인:: True


In [ ]:
arr_2d = arr_1d.reshape(3, 4)
arr_line = np.ravel(arr_2d)

print(arr_line)

# 메모리 공유 확인
print(f'메모리 공유 확인:: {np.shares_memory(arr_2d,arr_line)}')



[ 0  1  2  3  4  5  6  7  8  9 10 11]
메모리 공유 확인:: True


In [120]:
a = np.array([[1, 2, 3]])
print(f'a={a}')                                # a=[[1 2 3]]

b = np.array([[4, 5, 6]])
print(f'b={b}')                                # b=[[4 5 6]]

print(np.r_[a,b])                              # [[1 2 3]                                                  [4 5 6]]

v_row = np.vstack([a,b])
print(f'v_row:: {v_row}')                      # v_row:: [[1 2 3][4 5 6]]

concat_row = np.concatenate((a, b), axis=0)    # axis = 0
print(f'concat_row:: {concat_row}')            # concat_row:: [[1 2 3][4 5 6]]

a=[[1 2 3]]
b=[[4 5 6]]
[[1 2 3]
 [4 5 6]]
v_row:: [[1 2 3]
 [4 5 6]]
concat_row:: [[1 2 3]
 [4 5 6]]


In [121]:
a = np.array([[1, 2, 3]])
print(f'a={a}')                                # a=[[1 2 3]]

b = np.array([[4, 5, 6]])
print(f'b={b}')                                # b=[[4 5 6]]

print(np.c_[a,b])                              # [[1 2 3 4 5 6]]

h_col = np.hstack([a,b])
print(f'h_col:: {h_col}')                      # h_col:: [[1 2 3 4 5 6]]

concat_col = np.concatenate((a, b), axis=1)    # axis = 1
print(f'concat_col:: {concat_col}')            # concat_col:: [[1 2 3 4 5 6]]

a=[[1 2 3]]
b=[[4 5 6]]
[[1 2 3 4 5 6]]
h_col:: [[1 2 3 4 5 6]]
concat_col:: [[1 2 3 4 5 6]]


In [ ]:
a = np.array([1, 2, 3])
print(f'a={a}')

b = np.array([4, 5, 6])
print(f'b={b}')

print(np.c_[a, b])

h_col = np.hstack([a, b])
print(f'h_col:: {h_col}')

AxisError: axis 1 is out of bounds for array of dimension 1
concat_col = np.concatenate((a, b), axis=1)

a=[1 2 3]
b=[4 5 6]
[[1 4]
 [2 5]
 [3 6]]
h_col:: [1 2 3 4 5 6]


AxisError: axis 1 is out of bounds for array of dimension 1

In [123]:

# 1차원 12개 원소 배열을 3행 4열 2차원 배열로 변경
arr_1d = np.arange(12)
arr_2d = arr_1d.reshape(3, 4)

# 메모리 공유 확인:: True
print(f'메모리 공유 확인:: {np.shares_memory(arr_1d ,arr_2d)}') 

# 행의 크기는 2로 지정하고, 열의 크기는 자동 계산(-1)하여 배치
arr_auto = arr_1d.reshape(2, -1)  # 결과적으로 2행 6열로 자동 변환됨

# 메모리 공유 확인:: True
print(f'메모리 공유 확인:: {np.shares_memory(arr_1d,arr_auto)}')

arr_2d = arr_1d.reshape(3, 4)
arr_line= np.ravel(arr_2d)

# [ 0  1  2  3  4  5  6  7  8  9 10 11]
print(arr_line)

#메모리 공유 확인:: True
print(f'메모리 공유 확인:: {np.shares_memory(arr_2d, arr_line)}')


메모리 공유 확인:: True
메모리 공유 확인:: True
[ 0  1  2  3  4  5  6  7  8  9 10 11]
메모리 공유 확인:: True


In [125]:
a = np.array([1, 2, 3])
print(f'a={a}')           # a=[1 2 3]      

b = np.array([4, 5, 6])
print(f'b={b}')           # b=[4 5 6]

print(np.r_[a,b])

v_row = np.vstack([a,b])
print(f'v_row:: {v_row}')     # h_row:: [[1 2 3][4 5 6]]

concat_row = np.concatenate((a, b), axis=0)  # axis = 0
print(f'concat_row:: {concat_row}') # concat_row:: [1 2 3 4 5 6]

a=[1 2 3]
b=[4 5 6]
[1 2 3 4 5 6]
v_row:: [[1 2 3]
 [4 5 6]]
concat_row:: [1 2 3 4 5 6]


In [127]:
a = np.array([1, 2, 3])
print(f'a={a}')                                # a=[1 2 3]

b = np.array([4, 5, 6])
print(f'b={b}')                                # b=[4 5 6]

print(np.c_[a,b])                              # [[1 4]
                                               #  [2 5]
                                               #  [3 6]]

h_col = np.hstack([a,b])
print(f'h_col:: {h_col}')                      # h_col:: [1 2 3 4 5 6]

# AxisError: axis 1 is out of bounds for array of dimension 1
# concat_col = np.concatenate((a, b), axis=1)    # axis = 1

a=[1 2 3]
b=[4 5 6]
[[1 4]
 [2 5]
 [3 6]]
h_col:: [1 2 3 4 5 6]


In [128]:
a = np.arange(12).reshape(3,4)
print(a)
x, y = np.split(a, 2, axis = 1)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [129]:
# 2차원이면 3차원으로 증가한다.
b = np.stack((x,y), axis = 0)   # 합치는 방향 설정 - axis
print(b.shape) # 2차원(m, n) => 3차원(2, m, n)
print(b)

(2, 3, 2)
[[[ 0  1]
  [ 4  5]
  [ 8  9]]

 [[ 2  3]
  [ 6  7]
  [10 11]]]


In [130]:
b = np.stack((x,y), axis = 1)
print(b.shape) # 2차원(m, n) => 3차원(m,2, n)
print(b)

(3, 2, 2)
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [131]:
c = np.concatenate((x, y), axis=0)
print(c.shape)
print(c)

(6, 2)
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [ 2  3]
 [ 6  7]
 [10 11]]


In [132]:
c = np.concatenate((x, y), axis=0)
print(c.shape)
print(c)

(6, 2)
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [ 2  3]
 [ 6  7]
 [10 11]]


In [133]:
c = np.concatenate((x, y), axis=1)
print(c.shape)
print(c)

(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [136]:
c = np.concatenate((x, y), axis=1)
print(c.shape)
print(c)

(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
x = np.arange(18)
print(f'x::{x}')

x = x.reshape(-1, 6)        # arange와 reshape 의 개수는 동일해야 된다.
print(f'x::{x}')            # '-'마이너스 값을 주면 뒤의 6에의해 앞의 행의 갯수가 구해진다.

print(np.hsplit(x, 3))
print(np.hsplit(x, (2,4)))

print(np.split(x, 3, axis=1))
print(np.split(x, (2, 4), axis=1))



x::[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
x::[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]


In [138]:
x = np.arange(18)
print(f'x::{x}')

x = x.reshape(-1, 6)
print(f'x::{x}')

print(np.vsplit(x, 3))
print(np.vsplit(x, (1,2)))

print(np.split(x, 3, axis=0))
print(np.split(x, (1, 2), axis=0))

x::[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
x::[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]


## 2.7 배열의 차원 확장 및 축소

### **2.7.1 차원 확장 (Expanding Dimensions)**

기존 데이터는 유지하면서 **새로운 축(Axis)을 추가**해 차원을 늘리는 방법입니다. (예: $1D \rightarrow 2D$, $2D \rightarrow 3D$)
**① `np.newaxis` (슬라이싱 기법)**
가장 많이 사용되는 직관적인 방식입니다. 원하는 축 위치에 `np.newaxis`를 넣어 새로운 차원을 만든다.

In [140]:
import numpy as np

arr = np.array([1, 2, 3]) # shape: (3,)

# 행 방향(axis 0) 확장 -> shape: (1, 3)
row_vec = arr[np.newaxis, :]

# 열 방향(axis 1) 확장 -> shape: (3, 1)
col_vec = arr[:, np.newaxis]

print("행벡터:\n", row_vec)
print("열벡터:\n", col_vec)

행벡터:
 [[1 2 3]]
열벡터:
 [[1]
 [2]
 [3]]


In [141]:
print(np.newaxis is None)

a = np.arange(12).reshape(3, 4)
print(a)

True
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [142]:
b = a[:, :, None]
print(b.shape)
print(b)

(3, 4, 1)
[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]]


### ② `np.expand_dims(a, axis)`

명시적으로 지정한 `axis` 위치에 차원을 1개 추가한다.

In [143]:
import numpy as np

arr = np.array([1, 2, 3])

e0 = np.expand_dims(arr, axis=0)
e1 = np.expand_dims(arr, axis=1)
print("e0.shape :", e0.shape)
print("e1.shape :", e1.shape)

e0.shape : (1, 3)
e1.shape : (3, 1)


### 2.7.2 차원 축소 (Squeezing / Flattening Dimensions)

필요 없거나 크기가 1인 차원을 **제거/압축**하는 방법이다.

### ① `np.squeeze(a, axis=None)`

크기가 1인 차원(Dummy Dimension)을 자동으로 찾아서 제거해 준다. (`axis`를 지정하여 특정 1인 차원만 쥐어짤 수도 있다.)

In [144]:
import numpy as np

# shape: (1, 3, 1) 인 3차원 배열
arr_3d = np.array([[[1], [2], [3]]])

# 크기가 1인 모든 차원 축소 -> shape: (3,)
squeezed = np.squeeze(arr_3d)

print("원래 shape:", arr_3d.shape) # (1, 3, 1)
print("축소 후 shape:", squeezed.shape) # (3,)
print("결과:", squeezed) # [1 2 3]

원래 shape: (1, 3, 1)
축소 후 shape: (3,)
결과: [1 2 3]


### ② `ravel()` / `flatten()` / `reshape(-1)` (평탄화: 1차원 변환)

다차원 배열을 **1차원 배열로 완전히 펼칠 때** 사용합니다.

- `ravel()`: 원본의 뷰(View)를 반환 (메모리 절약, 속도 빠름)
- `flatten()`: 원본을 복사(Copy)하여 반환
- `reshape(-1)`: 가장 범용적인 평탄화 방식

# 3. 벡터화 연산과 브로드캐스팅 (핵심 구간)

**강의 목표**: 반복문(`for`) 없는 코딩의 핵심인 '벡터화 연산'과 '브로드캐스팅'의 원리를 마스터한다.

## 3.1 **유니버설 함수 (ufunc)**: 사칙연산, 제곱근(`sqrt`), 지수/로그(`exp`, `log`)의 요소별(Element-wise) 고속 연산

유니버설 함수(Universal Functions, 줄여서 ufunc)는 NumPy의 가장 핵심적인 기능 중 하나로, **`ndarray` 배열의 모든 원소(element)에 대해 빠르게 연산을 수행하는 함수**를 의미이다.

**1) ufunc의 핵심 특징**

- **원소별 연산 (Element-wise Operations)**
    
    파이썬의 기본 반복문(`for` 문)을 작성하지 않아도, 배열의 각 원소에 동시에 함수가 적용된다.
    
- **C언어 기반의 속도 (Fast Speed)**
    
    내부적으로 C언어로 구현되어 있어 순수한 파이썬 코드로 반복문을 돌리는 것보다 연산 속도가 훨씬 빠르다.
    
- **브로드캐스팅 지원 (Broadcasting)**
    
    모양이 완전히 같지 않은 배열끼리도 일정한 규칙(브로드캐스팅)에 따라 연산을 맞춰서 수행해 다.

**2) ufunc의 분류**

ufunc는 **입력받는 배열의 개수**에 따라 크게 두 가지로 나뉩니다.

① 단항 유니버설 함수 (Unary ufunc)

- **입력:** 1개의 배열
- **기능:** 배열의 각 원소에 단독으로 연산을 수행합니다.
- **주요 함수:**
    - `np.abs()`: 절대값
    - `np.sqrt()`: 제곱근
    - `np.exp()`, `np.log()`: 지수 및 로그
    - `np.sin()`, `np.cos()`: 삼각함수
    - `np.ceil()`, `np.floor()`: 올림과 내림

② 이항 유니버설 함수 (Binary ufunc)

- **입력:** 2개의 배열 (또는 배열과 스칼라)
- **기능:** 두 배열의 같은 위치에 있는 원소끼리 짝을 지어 연산을 수행합니다.
- **주요 함수:**
    - `np.add()`, `np.subtract()`: 덧셈, 뺄셈 (산술 연산)
    - `np.maximum()`, `np.minimum()`: 두 배열 중 크거나 작은 값 선택
    - `np.greater()`, `np.equal()`: 원소별 대소/등가 비교 연산
    - `np.copysign()`: 한 배열의 부호를 다른 배열에 복사

In [145]:
import numpy as np
arr = [-2.1, 0, 1.5, 3.7]

result_python = [abs(x) for x in arr]



In [146]:
result_ufunc = np.abs(arr)

In [147]:
#  1개의 배열에 대한 ufunc (Unary Universal Functions)


import numpy as np

# 입력 데이터
x = np.array([-2.1, 0, 1.5, 3.7])

# ==============================================================================
# 1. 원소별 산술 연산 (element-wise arithmetic computation)
# ==============================================================================
print(np.abs(x))        # 절대값 계산 -> 출력: [2.1 0.  1.5 3.7]
print(np.fabs(x))       # 절대값 계산 (부동소수점 전용) -> 출력: [2.1 0.  1.5 3.7]

print(np.ceil(x))       # 올림 -> 출력: [-2.  0.  2.  4.]
print(np.floor(x))      # 내림 -> 출력: [-3.  0.  1.  3.]

print(np.modf(x))       # 소수 부분과 정수 부분 분리 -> 출력: (array([-0.1,  0. ,  0.5,  0.7]), array([-2.,  0.,  1.,  3.]))
print(np.rint(x))       # 가장 가까운 정수로 반올림 -> 출력: [-2.  0.  2.  4.]

print(np.log(x))        # 자연로그(ln) -> 출력: [       nan       -inf 0.40546511 1.30833282]
print(np.log10(x))      # 상용로그(log10) -> 출력: [       nan       -inf 0.17609126 0.56820172]
print(np.log2(x))       # 로그(log2) -> 출력: [       nan       -inf 0.5849625  1.88752538]
print(np.log1p(x))      # log(1 + x) 계산 -> 출력: [       nan 0.         0.91629073 1.54756251]

print(np.exp(x))        # 지수함수 (e^x) -> 출력: [ 0.12245643  1.          4.48168907 40.44730436]
print(np.sqrt(x))       # 제곱근 -> 출력: [       nan 0.         1.22474487 1.92353841]
print(np.square(x))     # 제곱 (x^2) -> 출력: [ 4.41  0.    2.25 13.69]


# ==============================================================================
# 2. 불리언 배열 반환 (returns boolean array)
# ==============================================================================
print(np.isnan(x))       # NaN(결측치) 여부 검사 -> 출력: [False False False False]
print(np.isfinite(x))    # 유효한 숫자(유한수) 여부 검사 -> 출력: [ True  True  True  True]
print(np.logical_not(x)) # 논리 부정 (Not) -> 출력: [False  True False False]


# ==============================================================================
# 3. 부호 반환 (returns the sign of each element)
# ==============================================================================
print(np.sign(x))       # 각 원소의 부호 (양수:1, 0:0, 음수:-1) -> 출력: [-1.  0.  1.  1.]


# ==============================================================================
# 4. 삼각함수 및 역삼각함수 (regular or inverse trigonometric functions)
# ==============================================================================
print(np.sin(x))        # 사인 (sin) -> 출력: [-0.86320937  0.          0.99749499 -0.52983614]
print(np.cos(x))        # 코사인 (cos) -> 출력: [-0.5048461   1.          0.0707372  -0.84810002]
print(np.tan(x))        # 탄젠트 (tan) -> 출력: [ 1.7098674   0.         14.10141995  0.62473215]

print(np.arcsin(x))     # 아크사인 (arcsin) -> 출력: [       nan 0.                nan        nan]
print(np.arccos(x))     # 아크코사인 (arccos) -> 출력: [       nan 1.57079633        nan        nan]
print(np.arctan(x))     # 아크탄젠트 (arctan) -> 출력: [-1.12586589  0.          0.98279372  1.30658742]

[2.1 0.  1.5 3.7]
[2.1 0.  1.5 3.7]
[-2.  0.  2.  4.]
[-3.  0.  1.  3.]
(array([-0.1,  0. ,  0.5,  0.7]), array([-2.,  0.,  1.,  3.]))
[-2.  0.  2.  4.]
[       nan       -inf 0.40546511 1.30833282]
[       nan       -inf 0.17609126 0.56820172]
[       nan       -inf 0.5849625  1.88752527]
[       nan 0.         0.91629073 1.54756251]
[ 0.12245643  1.          4.48168907 40.44730436]
[       nan 0.         1.22474487 1.92353841]
[ 4.41  0.    2.25 13.69]
[False False False False]
[ True  True  True  True]
[False  True False False]
[-1.  0.  1.  1.]
[-0.86320937  0.          0.99749499 -0.52983614]
[-0.5048461   1.          0.0707372  -0.84810003]
[ 1.70984654  0.         14.10141995  0.62473308]
[nan  0. nan nan]
[       nan 1.57079633        nan        nan]
[-1.12637712  0.          0.98279372  1.3068326 ]


C:\Users\playdata2\AppData\Local\Temp\ipykernel_6256\3315418919.py:21: RuntimeWarning: divide by zero encountered in log
  print(np.log(x))        # 자연로그(ln) -> 출력: [       nan       -inf 0.40546511 1.30833282]
C:\Users\playdata2\AppData\Local\Temp\ipykernel_6256\3315418919.py:21: RuntimeWarning: invalid value encountered in log
  print(np.log(x))        # 자연로그(ln) -> 출력: [       nan       -inf 0.40546511 1.30833282]
C:\Users\playdata2\AppData\Local\Temp\ipykernel_6256\3315418919.py:22: RuntimeWarning: divide by zero encountered in log10
  print(np.log10(x))      # 상용로그(log10) -> 출력: [       nan       -inf 0.17609126 0.56820172]
C:\Users\playdata2\AppData\Local\Temp\ipykernel_6256\3315418919.py:22: RuntimeWarning: invalid value encountered in log10
  print(np.log10(x))      # 상용로그(log10) -> 출력: [       nan       -inf 0.17609126 0.56820172]
C:\Users\playdata2\AppData\Local\Temp\ipykernel_6256\3315418919.py:23: RuntimeWarning: divide by zero encountered in log2
  print(np.log2(x))       

## 3.2 **브로드캐스팅 (Broadcasting) 규칙**: 서로 크기가 다른 배열 간의 연산이 가능해지는 마법 같은 원리와 조건

브로드캐스팅(Broadcasting)은 NumPy에서 **모양(Shape)이 서로 다른 배열끼리 연산(덧셈, 뺄셈, 곱셈 등)을 가능하게 만들어주는 핵심 기능이**다.

원래 배열 연산은 크기와 모양이 완벽히 같아야 하지만, NumPy는 특정 조건이 맞으면 작은 배열을 자동으로 큰 배열의 모양에 맞춰 확장(복사)하여 연산을 수행한다.

### **3.2.1  브로드캐스팅의 규칙 (Broadcasting Rules)**

두 배열 A와 B가 연산 가능하려면, **뒤쪽 차원(가장 오른쪽 축)부터 비교**하여 다음 **두 조건 중 하나**를 만족해야  한다.
① **두 차원의 크기가 같다.**
②  **둘 중 하나의 차원 크기가 1이다.** (스칼라도 크기가 1인 차원으로 취급됨)

💡 **비교 예시:**

- `Shape (4, 3)` 과 `Shape (3,)`
$\rightarrow$ 뒤쪽 차원부터 비교: `3 == 3` (같음) / 앞 차원은 1로 간주되어 연산 가능!
- `Shape (4, 3)` 과 `Shape (4,)`
$\rightarrow$ 뒤쪽 차원 비교: `3 != 4` (다르고 1도 아님) $\rightarrow$ **연산 불가능 (Error)**

In [148]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr + 10)  # 출력: [11 12 13]

[11 12 13]


In [151]:
import numpy as np

matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])  # shape: (2, 3)
row_vec = np.array([10, 20, 30]) # shape: (3,)

print(matrix + row_vec)
# 출력:
# [[11 22 33]
#  [14 25 36]]

[[11 22 33]
 [14 25 36]]


In [152]:
import numpy as np

col_vec = np.array([[1], 
                    [2], 
                    [3]])        # shape: (3, 1)
row_vec = np.array([10, 20, 30]) # shape: (3,) -> (1, 3)으로 브로드캐스팅

print(col_vec + row_vec)
# 출력:
# [[11 21 31]
#  [12 22 32]
#  [13 23 33]]

[[11 21 31]
 [12 22 32]
 [13 23 33]]


### 3.2.3 브로드캐스팅의 장점

**① 메모리 효율성:** 데이터를 실제로 메모리에 복사하여 늘리지 않고, 연산 시점에 가상으로 맞춰 처리하므로 **메모리를 거의 차지하지 않는다.**  => 메모리를 차지 하지만 절약할 수 있다.

**② 연산 속도:** 반복문(`for` 문) 없이 C언어 수준에서 한 번에 연산하므로 **속도가 훨씬 빠릅니다.**

**③ 코드의 간결성:** 데이터 형상을 맞추기 위한 부가적인 코드가 줄어들어 **가독성이 좋아집니다.**

 **4) 암기 꿀팁 (헷갈릴 때 기억하는 방법)"지우개 법칙 (축을 없앤다!)"**

- `shape (3, 3)` 형태의 2차원 배열이 있을 때:
  - `axis=0`으로 연산하면 (3, 3)중  첫 번째 3(행 축)이 지워져 결과는 **`shape (3,)`** (세로 연산 결과)가 된다.
  - `axis=1`로 연산하면 (3, 3) 중 두 번째 3(열 축)이 지워져 결과는 **`shape (3,)`** (가로 연산 결과)가 된다.

즉, **`axis=n`은 "N번째 차원 방향으로 데이터들을 뭉개서 하나로 합친다!"** 라고 이해하시면 가장 쉽다.

3.5 위치 찾기: **np.argmax(), np.argmin()**을 활용한 최대/최소값의 인덱스 번호 추출

4.2 정렬 및 중복 제거: np.sort(), 인덱스를 반환하는 argsort(), 유일한 값 추출 np.unique()

In [153]:
import numpy as np

# 1. Shape (4,) 크기의 1차원 배열 생성
arr = np.array([1, 2, 3, 4])

# 2. 스칼라(단일 값) 정의
scalar = 1

# 3. 배열과 스칼라 간의 덧셈 연산 (브로드캐스팅 발생)
#    스칼라 값 '1'이 배열의 크기인 (4,)에 맞게 [1, 1, 1, 1]로 확장되어 각 원소별로 더해집니다.
result = arr + scalar

# ==============================================================================
# 출력 및 결과
# ==============================================================================
print(arr)         # 입력 배열 출력 -> 출력: [1 2 3 4]
print(scalar)      # 더해지는 스칼라 값 출력 -> 출력: 1
print(result)      # 연산 결과 출력 -> 출력: [2 3 4 5]

# Shape(모양) 확인
print(arr.shape)   # 입력 배열의 shape -> 출력: (4,)
print(result.shape)# 결과 배열의 shape -> 출력: (4,)

[1 2 3 4]
1
[2 3 4 5]
(4,)
(4,)


In [154]:
import numpy as np

# 1. shape (4, 3) 크기의 2차원 배열 생성
matrix = np.array([[ 0,  1,  2],
                   [ 3,  4,  5],
                   [ 6,  7,  8],
                   [ 9, 10, 11]])

# 2. shape (3,) 크기의 1차원 배열 생성
row_vec = np.array([0, 1, 2])

# 3. 2차원 배열과 1차원 배열의 덧셈 연산 (브로드캐스팅 발생)
#    shape (3,) 배열이 axis 0(행 방향, 아래쪽)으로 확장되어 
#    [[0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2]]의 형태로 각 행에 더해집니다.
result = matrix + row_vec

# ==============================================================================
# 출력 및 결과
# ==============================================================================
print(matrix)
# 출력:
# [[ 0  1  2]
#  [ 3  4  5]
#  [ 6  7  8]
#  [ 9 10 11]]

print(row_vec)
# 출력: [0 1 2]

print(result)
# 출력:
# [[ 0  2  4]
#  [ 3  5  7]
#  [ 6  8 10]
#  [ 9 11 13]]

# Shape(모양) 확인
print(matrix.shape)   # 2차원 배열 크기 -> 출력: (4, 3)
print(row_vec.shape)  # 1차원 배열 크기 -> 출력: (3,)
print(result.shape)   # 연산 결과 배열 크기 -> 출력: (4, 3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]
(4, 3)
(3,)
(4, 3)


In [155]:
import numpy as np

# 1. shape (4, 3) 크기의 2차원 배열 생성
matrix = np.array([[ 0,  1,  2],
                   [ 3,  4,  5],
                   [ 6,  7,  8],
                   [ 9, 10, 11]])

# 2. shape (4, 1) 크기의 2차원 열벡터(Column Vector) 생성
col_vec = np.array([[0],
                    [1],
                    [2],
                    [3]])

# 3. 2차원 배열 간의 덧셈 연산 (브로드캐스팅 발생)
#    shape (4, 1) 배열이 axis 1(열 방향, 오른쪽)으로 확장되어 
#    [[0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3]] 형태가 되어 각 열에 더해집니다.
result = matrix + col_vec

# ==============================================================================
# 출력 및 결과
# ==============================================================================
print(matrix)
# 출력:
# [[ 0  1  2]
#  [ 3  4  5]
#  [ 6  7  8]
#  [ 9 10 11]]

print(col_vec)
# 출력:
# [[0]
#  [1]
#  [2]
#  [3]]

print(result)
# 출력:
# [[ 0  1  2]
#  [ 4  5  6]
#  [ 8  9 10]
#  [12 13 14]]

# Shape(모양) 확인
print(matrix.shape)   # 첫 번째 2차원 배열 크기 -> 출력: (4, 3)
print(col_vec.shape)  # 두 번째 2차원 배열(열벡터) 크기 -> 출력: (4, 1)
print(result.shape)   # 연산 결과 배열 크기 -> 출력: (4, 3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
(4, 3)
(4, 1)
(4, 3)


## 4.3 **선형대수 기초 (Linear Algebra)**:

선형대수학은 벡터 공간, 선형 변환, 행렬 등을 연구하는 수학의 한 분야이다. 데이터 과학, 머신러닝, 인공지능 분야에서 핵심이 되는 수학적 기초를 제공한다.

### 1) 주요 개념 정리

- **스칼라(Scalar)**: 크기만을 가지는 단일 숫자이다.
- **벡터(Vector)**: 크기와 방향을 동시에 가지며, 공간 상의 한 점이나 방향을 나타낸다.
- **행렬(Matrix)**: 숫자들을 가로(행)와 세로(열)로 배열한 2차원 구조이다.
- **텐서(Tensor)**: 행렬을 3차원 이상으로 확장한 다차원 배열이다.
- **선형 변환(Linear Transformation)**: 공간 상의 벡터를 다른 벡터로 매핑할 때, 가산성과 제차성을 만족하는 변환이다.
- **고유값과 고유벡터(Eigenvalue & Eigenvector)**: 선형 변환을 적용했을 때 방향은 바뀌지 않고 크기만 변하는 벡터를 고유벡터라 하며, 그 크기의 변화 비율을 고유값이라 한다.

In [156]:
import numpy as np

# 1. 벡터 및 행렬 생성
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

A = np.array([[1, 2], 
              [3, 4]])

B = np.array([[5, 6], 
              [7, 8]])

# 2. 벡터 내적 (Dot Product)
dot_product = np.dot(v1, v2)
print("Vector Dot Product:")
print(dot_product)
# 출력: 32 (1*4 + 2*5 + 3*6)

# 3. 행렬 곱셈 (Matrix Multiplication)
matrix_mul = np.matmul(A, B) # 또는 A @ B
print("\nMatrix Multiplication (A @ B):")
print(matrix_mul)
# 출력:
# [[19 22]
#  [43 50]]

# 4. 전치 행렬 (Transpose Matrix)
A_transpose = A.T
print("\nTranspose of Matrix A:")
print(A_transpose)
# 출력:
# [[1 3]
#  [2 4]]

# 5. 역행렬 (Inverse Matrix)
A_inv = np.linalg.inv(A)
print("\nInverse of Matrix A:")
print(A_inv)
# 출력:
# [[-2.   1. ]
#  [ 1.5 -0.5]]

# 6. 행렬식 (Determinant)
det_A = np.linalg.det(A)
print("\nDeterminant of Matrix A:")
print(det_A)
# 출력: -2.0 (1*4 - 2*3)

# 7. 고유값 및 고유벡터 (Eigenvalues & Eigenvectors)
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues of A:")
print(eigenvalues)
# 출력: [-0.37228132  5.37228132]

print("\nEigenvectors of A:")
print(eigenvectors)
# 출력:
# [[-0.82456484 -0.41597356]
#  [ 0.56576746 -0.90937671]]

Vector Dot Product:
32

Matrix Multiplication (A @ B):
[[19 22]
 [43 50]]

Transpose of Matrix A:
[[1 3]
 [2 4]]

Inverse of Matrix A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Determinant of Matrix A:
-2.0000000000000004

Eigenvalues of A:
[-0.37228132+0.j  5.37228132+0.j]

Eigenvectors of A:
[[-0.82456484+0.j -0.41597356+0.j]
 [ 0.56576746+0.j -0.90937671+0.j]]


In [157]:
import numpy as np

# 1. 벡터 및 행렬 생성
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

A = np.array([[1, 2], 
              [3, 4]])

B = np.array([[5, 6], 
              [7, 8]])

In [ ]:
# 2. 벡터 내적 (Dot Product)  : 같은 위치의 행렬 값끼리 곱해서 더한 값
dot_product = np.dot(v1, v2)
print("Vector Dot Product:")
print(dot_product)          # 출력: 32 (1*4 + 2*5 + 3*6)

Vector Dot Product:
32


In [159]:
# 3. 행렬 곱셈 (Matrix Multiplication)
matrix_mul = np.matmul(A, B) # 또는 A @ B
print("\nMatrix Multiplication (A @ B):")
print(matrix_mul)
# 출력:
# [[19 22]
#  [43 50]]


Matrix Multiplication (A @ B):
[[19 22]
 [43 50]]


In [160]:
# 4. 전치 행렬 (Transpose Matrix)
A_transpose = A.T
print("\nTranspose of Matrix A:")
print(A_transpose)
# 출력:
# [[1 3]
#  [2 4]]


Transpose of Matrix A:
[[1 3]
 [2 4]]


In [161]:
# 5. 역행렬 (Inverse Matrix)
A_inv = np.linalg.inv(A)
print("\nInverse of Matrix A:")
print(A_inv)
# 출력:
# [[-2.   1. ]
#  [ 1.5 -0.5]]



Inverse of Matrix A:
[[-2.   1. ]
 [ 1.5 -0.5]]


행렬 곱(`np.dot()`, `@` 연산자), 전치행렬(`.T`)

- ndarray에서 행렬곱 연산자 @ 이다.
- python 재단에서 numpy를 위해 만들어준 연산자이다

In [162]:
import numpy as np

# 1. shape (3, 5) 크기의 2차원 배열 생성
a = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])

# 2. 전치(Transpose) 및 축 교환(Swap Axes) 연산 (모두 동일한 결과 반환)
# ① .T 속성 사용
transposed_T = a.T

# ② np.transpose() 함수 사용
transposed_func = np.transpose(a)

# ③ np.swapaxes() 함수 사용 (0번 축과 1번 축을 맞바꿈)
swapped = np.swapaxes(a, 0, 1)

# ==============================================================================
# 출력 및 결과
# ==============================================================================
print(a)
# 원본 배열 출력 (shape: 3, 5):
# [[ 0  1  2  3  4]
#  [ 5  6  7  8  9]
#  [10 11 12 13 14]]

# ① a.T -> 전치 행렬
print(transposed_T)
# 출력:
# [[ 0  5 10]
#  [ 1  6 11]
#  [ 2  7 12]
#  [ 3  8 13]
#  [ 4  9 14]]

# ② np.transpose(a) -> 전치 행렬
print(transposed_func)
# 출력:
# [[ 0  5 10]
#  [ 1  6 11]
#  [ 2  7 12]
#  [ 3  8 13]
#  [ 4  9 14]]

# ③ np.swapaxes(a, 0, 1) -> 축 맞바꿈
print(swapped)
# 출력:
# [[ 0  5 10]
#  [ 1  6 11]
#  [ 2  7 12]
#  [ 3  8 13]
#  [ 4  9 14]]

# Shape(모양) 확인 ( (3, 5) -> (5, 3)으로 변환 )
print(a.shape)            # 원본 크기 -> 출력: (3, 5)
print(transposed_T.shape) # 변환 후 크기 -> 출력: (5, 3)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
(3, 5)
(5, 3)


In [164]:
b = np.matrix([[1,2], [3,4]]) # 행렬 생성  [[1 2][3 4]]
print(b)

print(type(b))            # numpy.matrix

[[1 2]
 [3 4]]
<class 'numpy.matrix'>


배열은 @가능하지만 *은 사용 할 수 없다.

matrix는 * 와 @ 모두가 가능하다.

ndarray에서 행렬곱 연산자 @ 이다.  
python 재단에서 numpy를 위해 만들어준 연산자이다.

In [169]:
c = np.matrix([[1,2], [3,4]]) # 행렬 생성
print(c)

print(c)
print(c.shape)

print(c * c.T)
print(np.dot(c, c.T))  # 함수방법으로 np.dot( )함수를 사용할 수 있다.
print( c.dot(c.T) ) # 메소드(method) 방식
print(c @ c.T)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
(2, 2)
[[ 5 11]
 [11 25]]
[[ 5 11]
 [11 25]]
[[ 5 11]
 [11 25]]
[[ 5 11]
 [11 25]]


In [172]:
import numpy as np

# 1. 시드 고정 및 가상의 학생 성적 데이터셋 생성 (학생 5명, 과목 3개)
np.random.seed(42)
scores = np.random.randint(40, 101, size=(5, 3))

print("1. 원본 성적 데이터셋 (5명 x 3과목):")
print(scores)

# 2. 각 과목별 평균 및 표준편차 구하기 (axis=0: 세로/열 방향 연산)
subject_mean = np.mean(scores, axis=0)
subject_std = np.std(scores, axis=0)

print("\n2. 과목별 평균:")
print(subject_mean)

print("\n3. 과목별 표준편차:")
print(np.round(subject_std, 2))

# 3. 각 학생별 평균 구하기 (axis=1: 가로/행 방향 연산)
student_mean = np.mean(scores, axis=1)

print("\n4. 학생별 평균 점수:")
print(np.round(student_mean, 2))

# 4. 낙제점 수정하기 (60점 미만인 점수를 60점으로 일괄 수정)
# np.where(조건, 참일 때 값, 거짓일 때 값) 활용
fixed_scores = np.where(scores < 60, 60, scores)

print("\n5. 낙제점(60점 미만) 수정 후 데이터셋:")
print(fixed_scores)

1. 원본 성적 데이터셋 (5명 x 3과목):
[[ 78  91  68]
 [ 54  82  47]
 [100  60  78]
 [ 97  58  62]
 [ 50  50  63]]

2. 과목별 평균:
[75.8 68.2 63.6]

3. 과목별 표준편차:
[20.88 15.57 10.05]

4. 학생별 평균 점수:
[79.   61.   79.33 72.33 54.33]

5. 낙제점(60점 미만) 수정 후 데이터셋:
[[ 78  91  68]
 [ 60  82  60]
 [100  60  78]
 [ 97  60  62]
 [ 60  60  63]]


[예시 2] 단순 이미지 픽셀 데이터(3차원 배열)를 불러와 흑백 전환 및 크기 조절 전처리 구현

$(H, W, C)$ 구조의 3차원 RGB 이미지 데이터를 생성하여 표준 공식을 통한 흑백(Grayscale) 전환 및 다운샘플링(크기 조절)을 구현하는 코드이다.

In [173]:
import numpy as np

# 1. 가상의 RGB 이미지 픽셀 데이터 생성 (높이 4 x 너비 4 x 채널 3)
np.random.seed(100)
image_rgb = np.random.randint(0, 256, size=(4, 4, 3), dtype=np.uint8)

print("1. 원본 RGB 이미지 Shape:")
print(image_rgb.shape)

# 2. RGB 흑백 전환 (Grayscale Conversion)
# ITU-R BT.601 표준 공식: Y = 0.299*R + 0.587*G + 0.114*B
# 채널 축(axis 2)에 가중치를 내적(Dot Product)하거나 브로드캐스팅하여 계산함
weights = np.array([0.299, 0.587, 0.114])
image_gray = np.dot(image_rgb, weights).astype(np.uint8)

print("\n2. 흑백 전환 후 이미지 Shape:")
print(image_gray.shape)  # (4, 4)로 차원 축소됨

print("\n3. 흑백 이미지 픽셀 값:")
print(image_gray)

# 3. 이미지 크기 조절 (Downsampling / Resizing)
# 슬라이싱([::2, ::2])을 이용하여 가로/세로 픽셀을 2칸씩 스킵함으로써 크기를 1/2로 줄임
image_resized = image_gray[::2, ::2]

print("\n4. 크기 조절(2x2로 축소) 후 이미지 Shape:")
print(image_resized.shape)

print("\n5. 최종 축소된 이미지 픽셀 값:")
print(image_resized)

1. 원본 RGB 이미지 Shape:
(4, 4, 3)

2. 흑백 전환 후 이미지 Shape:
(4, 4)

3. 흑백 이미지 픽셀 값:
[[ 93  80 170  63]
 [175  87 124 128]
 [ 97 173  36  50]
 [ 89  73  33 139]]

4. 크기 조절(2x2로 축소) 후 이미지 Shape:
(2, 2)

5. 최종 축소된 이미지 픽셀 값:
[[ 93 170]
 [ 97  36]]


# 3. CRISP-DM 데이터 분석 방법론

**CRISP-DM(Cross Industry Standard Process for Data Mining)** 방법론은 1996년 유럽연합(EU)의 프로젝트로 시작되어 SPSS, NCR, Daimler-Benz 등이 참여하여 개발한 **데이터 마이닝 및 데이터 분석의 글로벌 표준 프로세스이**다. 

비즈니스 아이디어부터 최종 서비스 배포까지 데이터 분석 프로젝트를 성공적으로 이끌기 위한 체계적인 가이드를 제공한다.

## **3.1 CRISP-DM의 주요 특징**

**① 비즈니스 중심 (Business-Oriented)**
• 기술이나 알고리즘 중심이 아닌, **'비즈니스 문제를 어떻게 해결할 것인가'**에 초점을 맞춘다.  첫 단계와 마지막 단계 모두 비즈니스 가치와 연결된다. 

**② 반복과 피드백 (Iterative Process)**
• 일직선으로 진행되는 폭포수(Waterfall) 모델과 달리, 이전 단계의 문제점이나 새로운 인사이트를 바탕으로 **끊임없이 앞 단계로 되돌아가는 유기적인 순환 구조**를 가진다.

**③ 업계 독립성 (Industry-Independent)**
• 특정 분석 도구나 금융, 제조, 의료 등 특정 산업군에 종속되지 않아 **어떤 도구(Python, R, SQL 등)나 분야단에서도 범용적으로 적용**할 수 있다.

**④ 계층적 구조 (Hierarchical Structure)**
• 총 4개의 계층(단계 -> 일반 과제 -> 세부 과제 -> 프로세스 실행)으로 구성되어 있어, 실무자가 구체적으로 무엇을 해야 하는지 명확히 안내한다.

## 3.2 CRISP-DM의 6대 핵심 단계

**① 비즈니스 이해 (Business Understanding)**

- **내용**: 프로젝트의 목적과 요구사항을 비즈니스 관점에서 이해하고, 이를 **데이터 마이닝 문제로 변환**하여 초기 계획을 수립한다.
- **주요 작업**: 비즈니스 목표 설정, 상황 평가, 데이터 마이닝 목표 정의, 프로젝트 계획 수립
- **해당 작업 순서:** `[1] 문제 정의`
- **고혈압 프로젝트 예시:**
    - 비즈니스 목표: 고혈압 발병 여부 예측 및 관리
    - 타겟 변수: 고혈압 여부 (True/False 분류)
    - 성공 지표 결정: 실제 환자를 놓치지 않는 성능 지표 설정

**② 데이터 이해 (Data Understanding)**

- **내용**: 분석에 필요한 초기 데이터를 수집하고, 데이터의 속성을 파악하여 품질 문제를 식별하거나 숨겨진 인사이트를 찾아낸다.
- **주요 작업**: 초기 데이터 수집, 데이터 기술(Description), 데이터 탐색(EDA), 데이터 품질 검증
- **해당 작업 순서:** `[2] 데이터 수집`, `[3] 데이터 탐색 (EDA)`
- **고혈압 프로젝트 예시:**
    - 데이터 수집: 사내 또는 공공 건강검진 데이터 확보
    - 데이터 탐색: 연령, BMI 등 주요 신체 지표와 고혈압 간의 통계적 관계 및 상관관계 분석

**③ 데이터 준비 (Data Preparation)**

- **내용**: 수집된 원시 데이터(Raw Data)를 모델링 도구에 투입할 수 있도록 정제하고 변환하여 **최종 데이터셋을 구축**하는 단계이다. (전체 프로젝트에서 가장 많은 시간이 소요된다.)
- **주요 작업**: 데이터 선택(추출), 데이터 정제(결측치/이상치 처리), 데이터 구성(피처 엔지니어링), 데이터 통합, 데이터 포맷팅
- **해당 작업 순서:** `[4] 데이터 전처리`, `[5] 피처 엔지니어링`, `[6] 데이터 분할`
- **고혈압 프로젝트 예시:**
    - 전처리: 결측치 평균 대체, 수치 왜곡을 줄이기 위한 BMI 로그 변환
    - 피처 엔지니어링: 연속형 변수인 BMI와 연령을 특정 구간으로 묶는 그룹화(Binning) 작업
    - 데이터 분할: 모델 학습 및 검증을 위한 Train/Test 데이터 분리 (클래스 불균형 고려)

**④ 모델링 (Modeling)**

- **내용**: 목적에 맞는 다양한 분석 알고리즘을 선택하여 적용하고, 파라미터를 최적화합니다. 이 과정에서 데이터의 형태를 바꾸어야 할 때가 많아 **'③ 데이터 준비' 단계와 끊임없이 반복**됩니다.
- **주요 작업**: 모델링 기법 선택, 테스트 설계(Train/Test 분할), 모델 구축, 모델 평가
- **해당 작업 순서:** `[7] 모델 선택 및 학습`, `[8] 하이퍼파라미터 튜닝`
- **고혈압 프로젝트 예시:**
    - 모델 선택: RandomForestClassifier, XGBoostClassifier 등 분류 알고리즘 선정 및 학습
    - 튜닝: `GridSearchCV` 등을 활용해 `n_estimators`, `max_depth` 등 최적의 하이퍼파라미터 탐색

**⑤ 평가 (Evaluation)**

- **내용**: 구축된 모델이 **비즈니스의 목적을 달성하는지 검증**합니다. 모델의 통계적 성능(정확도 등)뿐만 아니라, 비즈니스 목표와 정렬되는지 종합적으로 평가하여 배포 여부를 결정한다.
- **주요 작업**: 결과 평가, 프로세스 검토, 다음 단계 결정
- **해당 작업 순서:** `[9] 모델 해석`, `[10] 모델 테스트 및 성능 평가`
- **고혈압 프로젝트 예시:**
    - 성능 평가: Accuracy(정확도) 및 고혈압 환자를 잘 잡아내는지 확인하는 Recall(재현율) 확인
    - 모델 해석: `SHAP` 라이브러리를 사용하여 고혈압 예측에 어떤 신체 지표가 가장 큰 영향을 주었는지 변수 중요도 분석

⑥ 배포 (Deployment)

- **내용**: 평가가 완료된 모델을 실제 운영 환경에 적용하여 비즈니스에 활용한다.  모델을 코드로 배포하거나 대시보드를 구축하며, 시간이 지남에 따라 모델 성능이 떨어지는 것을 막기 위한 모니터링 계획을 세운다.
- **주요 작업**: 배포 계획 수립, 모니터링 및 유지보수 계획 수립, 최종 보고서 작성, 프로젝트 검토
- **해당 작업 순서:** `[11] 모델 저장 및 배포`, `[12] 리포트 작성 및 결과 공유`
- **고혈압 프로젝트 예시:**
    - 모델 저장 및 배포: 학습된 모델 파일 저장 후 `Streamlit 대시보드` 구현 또는 `FastAPI REST API` 구축
    - 결과 공유: 분석 과정과 비즈니스적 시사점을 정리한 최종 리포트 작성 및 공유